# Generated by Django 2.2.5 on 2019-09-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_shoes_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleShoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('price1', models.CharField(max_length=20)),
                ('sole', models.CharField(max_length=20)),
                ('closure', models.CharField(max_length=20)),
                ('materialtype', models.CharField(max_length=20)),
                ('lifestyle', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='shoes',
            name='price1',
            field=models.CharField(max_length=20),
        ),
    ]
