# Generated by Django 2.2.5 on 2019-09-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20190921_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleshoes',
            name='img2',
            field=models.ImageField(default=1, upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='singleshoes',
            name='img3',
            field=models.ImageField(default=1, upload_to='pics'),
            preserve_default=False,
        ),
    ]
