# Generated by Django 2.2.5 on 2019-09-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20190922_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
