# Generated by Django 2.2.5 on 2019-09-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_shoes_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='category',
            field=models.CharField(default='casual', max_length=50),
            preserve_default=False,
        ),
    ]
