# Generated by Django 2.2.5 on 2019-09-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='item_json',
            field=models.CharField(default='a', max_length=5000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='address1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='address2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='city',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='orders',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='orders',
            name='state',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='orders',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='zipcode',
            field=models.CharField(max_length=30),
        ),
    ]
